language: java

sudo: false

cache:
  directories:
   - $HOME/.m2

before_script:
 - mvn dependency:copy-dependencies

script:
 - mvn verify
 - ant all

notifications:
  email: false

jdk:
 - openjdk8

