name: google-gin

on: [push]

jobs:
  verify:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11.0.6+10']

    steps:
    - name: git
      uses: actions/checkout@v2

    - name: java
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{matrix.java}}

    - name: maven
      run: ./mvnw -B clean verify --file pom.xml
